### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by k1651408** [dreamnettech/dreampower#75]
Says update available: 0.0.1 but update button doesn't work. 

1. Go to checkpoints
2. Click on update
3. Scroll down to Dreampower update available
4. Click on update
5. See Update failed
There was a problem trying to download the update, please verify that you are connected to the Internet. If the problem persists try to configure or temporarily disable your Firewall/Antivirus/VPN.

I don't have any firewalls or antivirus up and am obviously connected to the internet.

Can't use without updating.

**Comment by deeppppp** [comment]
That's an issue with DreamTime:
https://github.com/dreamnettech/dreamtime

not related to DreamPower

**Comment by DeepnudeEntusiast** [comment]
> Says update available: 0.0.1 but update button doesn't work.
> 
> Steps to reproduce the behavior:
> 
> 1. Go to checkpoints
> 2. Click on update
> 3. Scroll down to Dreampower update available
> 4. Click on update
> 5. See Update failed
>    There was a problem trying to download the update, please verify that you are connected to the Internet. If the problem persists try to configure or temporarily disable your Firewall/Antivirus/VPN.
> 
> I don't have any firewalls or antivirus up and am obviously connected to the internet.
> 
> Can't use without updating.

I know it's too late maybe but i solved the same issue downloading the zip file,after that i copied the whole content into the dreampower folder,also i copied to the same folder the updated checkpoints folder.  I need say an important point before launch again dreamtime. You need delete the preferences jason file. Because it's a bug of the latest dreamtime version
