### ISSUE TITLE
Google Colab?

### ISSUE THREAD

**Issue by rodrigoonline** [dreamnettech/dreampower#85]

**Comment by FirstDee** [comment]
I made one for v1.2.5, see:

* [Gist](https://gist.github.com/FirstDee/c3a94ff37e0561e597b65160aabbbc07)
* [Colab](https://colab.research.google.com/gist/FirstDee/c3a94ff37e0561e597b65160aabbbc07/dreamtime-v1.ipynb)

**Comment by ayushrox** [comment]
Hi! I am interested in learning computer vision and would like to learn and implement this paper, but because this is my first hands-on experience, I don't have a decent GPU. So I was hoping if anyone could share a Google colab notebook for the implementation of deepMOT.

link : https://github.com/yihongXU/deepMOT

I am facing trouble in setting up the environment as I don't have any background in Computer vision and the repo does not mention anything about a notebook.

**Comment by kolessios** [comment]
@ayushrox Hi, I think you've got a bit confused about what this repository is. This is a fork of the DeepNude algorithm whose code has been restructured and improved.

This repository does not contain any paper beyond a basic description of how the DeepNude algorithm works and like the original code we dont provide a way to train (or continue training) the data models.

Also, deepMOT has no relationship with DreamPower. 

You can get the latest version of Google Colab for this project on [this page](https://dreamtime.tech/docs/guide/google-colab), however, as I said before, this is only to use the project and it does not do much to learn or do advanced things like training.

To learn about computer vision you will have to see other projects. Sorry!

**Comment by ayushrox** [comment]
Got it thanks.
